/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author UNA
 */
public class frmSalir extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public frmSalir() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        txtMessageImage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JLabel();
        btnSi = new javax.swing.JPanel();
        txtbtnSi = new javax.swing.JLabel();
        btnNo = new javax.swing.JPanel();
        txtbtnNo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 236, 239));
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMessageImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/question_iconx64.gif"))); // NOI18N
        background.add(txtMessageImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 64, 64));

        txtMessage.setBackground(new java.awt.Color(0, 0, 0));
        txtMessage.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txtMessage.setText("¿Está seguro de que desea salir?");
        background.add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 310, 30));

        btnSi.setBackground(new java.awt.Color(55, 41, 72));
        btnSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSiMousePressed(evt);
            }
        });

        txtbtnSi.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtbtnSi.setForeground(new java.awt.Color(247, 236, 222));
        txtbtnSi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbtnSi.setText("Si");

        javax.swing.GroupLayout btnSiLayout = new javax.swing.GroupLayout(btnSi);
        btnSi.setLayout(btnSiLayout);
        btnSiLayout.setHorizontalGroup(
            btnSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtbtnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnSiLayout.setVerticalGroup(
            btnSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbtnSi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        background.add(btnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        btnNo.setBackground(new java.awt.Color(55, 41, 72));
        btnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNoMousePressed(evt);
            }
        });

        txtbtnNo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtbtnNo.setForeground(new java.awt.Color(247, 236, 222));
        txtbtnNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbtnNo.setText("No");

        javax.swing.GroupLayout btnNoLayout = new javax.swing.GroupLayout(btnNo);
        btnNo.setLayout(btnNoLayout);
        btnNoLayout.setHorizontalGroup(
            btnNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtbtnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnNoLayout.setVerticalGroup(
            btnNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbtnNo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        background.add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMouseEntered
        btnSi.setBackground(new Color(37, 27, 55));
        txtbtnSi.setForeground(new Color(255, 202, 202));
    }//GEN-LAST:event_btnSiMouseEntered

    private void btnSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMouseExited
        btnSi.setBackground(new Color(55, 41, 72));
        txtbtnSi.setForeground(new Color(255, 236, 239));
    }//GEN-LAST:event_btnSiMouseExited

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_backgroundMouseDragged

    private void btnSiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnSiMousePressed

    private void btnNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseEntered
        btnNo.setBackground(new Color(37, 27, 55));
        txtbtnNo.setForeground(new Color(255, 202, 202));
    }//GEN-LAST:event_btnNoMouseEntered

    private void btnNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseExited
        btnNo.setBackground(new Color(55, 41, 72));
        txtbtnNo.setForeground(new Color(255, 236, 239));
    }//GEN-LAST:event_btnNoMouseExited

    private void btnNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMousePressed
        Dashboard.abierto = false;
        this.dispose();
    }//GEN-LAST:event_btnNoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSalir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnNo;
    private javax.swing.JPanel btnSi;
    public static javax.swing.JLabel txtMessage;
    public static javax.swing.JLabel txtMessageImage;
    private javax.swing.JLabel txtbtnNo;
    private javax.swing.JLabel txtbtnSi;
    // End of variables declaration//GEN-END:variables
}
