/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui;


import Logica.GestorReservaciones;
import static Logica.Global.listaReservaciones;
import static Logica.Global.listaReservaciones;
import Logica.Reservaciones;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author UNA
 */
public class jpReservaciones extends javax.swing.JPanel {

    GestorReservaciones gestorReservaciones;
    /**
     * Creates new form jpReservaciones
     */
    public jpReservaciones() {
        initComponents();
        gestorReservaciones = new GestorReservaciones();
        gestorReservaciones.recuperarDeArchivo();
        tblReservaciones.setModel(gestorReservaciones.obtenerModeloTabla());
        lblTotal.setText("Total: " + tblReservaciones.getRowCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservaciones = new javax.swing.JTable();
        btnAgregar = new javax.swing.JPanel();
        txtbtnAgregar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        txtbtnEditar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        txtbtnEliminar = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JPanel();
        txtbtnImprimir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(650, 530));

        jPanel1.setBackground(new java.awt.Color(255, 236, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblReservaciones.setBackground(new java.awt.Color(255, 236, 239));
        tblReservaciones.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblReservaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID RENTA", "FECHA", "ID HABITACIÓN", "ID CLIENTE", "FORMAS DE PAGO", "TOTAL"
            }
        ));
        tblReservaciones.setOpaque(false);
        tblReservaciones.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblReservaciones.setShowGrid(true);
        jScrollPane1.setViewportView(tblReservaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 550));

        btnAgregar.setBackground(new java.awt.Color(55, 41, 72));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarMousePressed(evt);
            }
        });

        txtbtnAgregar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtbtnAgregar.setForeground(new java.awt.Color(247, 236, 222));
        txtbtnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbtnAgregar.setText("Agregar");

        javax.swing.GroupLayout btnAgregarLayout = new javax.swing.GroupLayout(btnAgregar);
        btnAgregar.setLayout(btnAgregarLayout);
        btnAgregarLayout.setHorizontalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtbtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnAgregarLayout.setVerticalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, -1, -1));

        btnEditar.setBackground(new java.awt.Color(55, 41, 72));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarMousePressed(evt);
            }
        });

        txtbtnEditar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtbtnEditar.setForeground(new java.awt.Color(247, 236, 222));
        txtbtnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbtnEditar.setText("Editar");

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtbtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(55, 41, 72));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });

        txtbtnEliminar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtbtnEliminar.setForeground(new java.awt.Color(247, 236, 222));
        txtbtnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbtnEliminar.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(txtbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbtnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        btnImprimir.setBackground(new java.awt.Color(55, 41, 72));
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImprimirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImprimirMouseExited(evt);
            }
        });

        txtbtnImprimir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtbtnImprimir.setForeground(new java.awt.Color(247, 236, 222));
        txtbtnImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbtnImprimir.setText("Imprimir");

        javax.swing.GroupLayout btnImprimirLayout = new javax.swing.GroupLayout(btnImprimir);
        btnImprimir.setLayout(btnImprimirLayout);
        btnImprimirLayout.setHorizontalGroup(
            btnImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImprimirLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtbtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnImprimirLayout.setVerticalGroup(
            btnImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbtnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("Reservaciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTotal.setFont(new java.awt.Font("Roboto", 3, 16)); // NOI18N
        lblTotal.setText("Total: 0");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        btnAgregar.setBackground(new Color(37, 27, 55));
        txtbtnAgregar.setForeground(new Color(255, 202, 202));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        btnAgregar.setBackground(new Color(55, 41, 72));
        txtbtnAgregar.setForeground(new Color(255, 236, 239));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnAgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMousePressed
        jpAgregarR agregar = new jpAgregarR();
        agregar.setSize(Dashboard.contenido.getWidth(), Dashboard.contenido.getHeight());
        agregar.setLocation(0, 0);

        Dashboard.contenido.removeAll();
        Dashboard.contenido.add(agregar, BorderLayout.CENTER);
        Dashboard.contenido.revalidate();
        Dashboard.contenido.repaint();
    }//GEN-LAST:event_btnAgregarMousePressed

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        btnEditar.setBackground(new Color(37, 27, 55));
        txtbtnEditar.setForeground(new Color(255, 202, 202));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        btnEditar.setBackground(new Color(55, 41, 72));
        txtbtnEditar.setForeground(new Color(255, 236, 239));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(37, 27, 55));
        txtbtnEliminar.setForeground(new Color(255, 202, 202));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(new Color(55, 41, 72));
        txtbtnEliminar.setForeground(new Color(255, 236, 239));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseEntered
        btnImprimir.setBackground(new Color(37, 27, 55));
        txtbtnImprimir.setForeground(new Color(255, 202, 202));
    }//GEN-LAST:event_btnImprimirMouseEntered

    private void btnImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseExited
        btnImprimir.setBackground(new Color(55, 41, 72));
        txtbtnImprimir.setForeground(new Color(255, 236, 239));
    }//GEN-LAST:event_btnImprimirMouseExited

    private void btnEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMousePressed
        jpAgregarR editar = new jpAgregarR();
        GestorReservaciones gestor = new GestorReservaciones();

        gestor.setFila(tblReservaciones.getSelectedRow());

        if (gestor.getFila() != -1) {
            editar.txtAgregar.setText("Editar");
            editar.setSize(Dashboard.contenido.getWidth(), Dashboard.contenido.getHeight());
            editar.setLocation(0, 0);

            Dashboard.contenido.removeAll();
            Dashboard.contenido.add(editar, BorderLayout.CENTER);
            Dashboard.contenido.revalidate();
            Dashboard.contenido.repaint();
            
            int pos = 0;
        for (Reservaciones reservaciones : listaReservaciones) {

            while (pos == tblReservaciones.getSelectedRow()) {                
                jpAgregarR.jcFechaActual.setDate(listaReservaciones.get(pos).getFecha());
                jpAgregarR.cbCliente.setSelectedItem(String.valueOf(listaReservaciones.get(pos).getIdCliente()));
                jpAgregarR.cbHabitacion.setSelectedItem(String.valueOf(listaReservaciones.get(pos).getIdHabi()));
                jpAgregarR.cbFormaPago.setSelectedIndex(Integer.parseInt(listaReservaciones.get(pos).getFormaPago()));
                jpAgregarR.cbOcupantesAdultos.setSelectedIndex( listaReservaciones.get(pos).getAdultos());
                jpAgregarR.cbOcupantesNinos.setSelectedIndex( listaReservaciones.get(pos).getNinnos());
                jpAgregarR.jcFechaInicial.setDate(listaReservaciones.get(pos).getFechaIni());
                jpAgregarR.jcFechaFinal.setDate(listaReservaciones.get(pos).getFechaFin());
                jpAgregarR.txtDiasHospedaje.setText(String.valueOf(listaReservaciones.get(pos).getDiasHos()));
                jpAgregarR.txtSubtotal.setText(String.valueOf(listaReservaciones.get(pos).getSubTotal()));
                jpAgregarR.cbDescuento.setSelectedIndex(listaReservaciones.get(pos).getDescuento());
                jpAgregarR.txtTotal.setText(String.valueOf(listaReservaciones.get(pos).getTotal()));
                jpAgregarR.setPos(pos);
                jpAgregarR.setValidarEH(listaReservaciones.get(pos).getIdHabi());
                pos ++;
            }
   
            pos ++;
            
            
        }
        pos = 0;
     
            
            
        }else {
            new frmMessagep().setVisible(true);
            frmMessagep.txtMessage.setText("Seleccione la reservación que desea editar");
            frmMessagep.txtMessageImage.setIcon(new ImageIcon(getClass().getResource("/resources/Icons/error_iconx64.gif")));
        }        
        
        
    }//GEN-LAST:event_btnEditarMousePressed

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        System.out.println("hola");
        GestorReservaciones gestor = new GestorReservaciones();
        gestor.setFila(tblReservaciones.getSelectedRow());
        if (gestor.getFila() != -1) {
            String idP = (tblReservaciones.getValueAt(gestor.getFila(), 0).toString());
            int resp = JOptionPane.showConfirmDialog(null,
                    "¿Esta seguro de eliminar al cliente seleccionado?", "Eliminar",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (resp == JOptionPane.YES_OPTION) {
                gestor.eliminar(idP);
                gestor.guardarEnArchivo();
                cargarDatos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione el cliente a eliminar",
                    "Eliminar", JOptionPane.ERROR_MESSAGE);
        }
        System.out.println("adios");
    }//GEN-LAST:event_btnEliminarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblReservaciones;
    private javax.swing.JLabel txtbtnAgregar;
    private javax.swing.JLabel txtbtnEditar;
    private javax.swing.JLabel txtbtnEliminar;
    private javax.swing.JLabel txtbtnImprimir;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        tblReservaciones.setModel(gestorReservaciones.obtenerModeloTabla());
        lblTotal.setText("Total: " + tblReservaciones.getRowCount());
    }


}
